#! /bin/sh
MESSAGE="Hello World"
SHORT_MESSAGE=hi
NUMBER=1
PI=3.142
OTHER_PI="3.142"
MIXED_MESSAGE=CALLME123
echo $MESSAGE
echo $SHORT_MESSAGE
echo $NUMBER
echo $PI
echo $OTHER_PI
echo $MIXED_MESSAGE
